<table border=0 cellspacing=0 cellpadding=0 width="100%" bgcolor="#333399">
<tr>
 <td><table border=0 cellspacing=1 cellpadding=0>
  <tr>
   <td bgcolor="#339933"><a CLASS="barlink"
    href="/emc/"
    onmouseover="mouseIn ('emc', 0)"
    onmouseout="mouseOut ('emc', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt=""
    name="emc"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>EMC Home</b></font></a>&nbsp;</td>

   <td bgcolor="#557733"><a CLASS="barlink"
    href="/emc/titles/?new"
    onmouseover="mouseIn ('newtitles', 0)"
    onmouseout="mouseOut ('newtitles', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt="| "
    name="newtitles"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>New Titles</b></font></a>&nbsp;</td>

   <td bgcolor="#885533"><a CLASS="barlink"
    href="/emc/titles/"
    onmouseover="mouseIn ('titles', 0)"
    onmouseout="mouseOut ('titles', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt="| "
    name="titles"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>All Titles</b></font></a>&nbsp;</td>

   <td bgcolor="#993333"><a CLASS="barlink"
    href="/emc/titles/?index"
    onmouseover="mouseIn ('abstracts', 0)"
    onmouseout="mouseOut ('abstracts', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt="| "
    name="abstracts"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>Abstracts</b></font></a>&nbsp;</td>

   <td bgcolor="#883355"><a CLASS="barlink"
    href="/emc/topics/"
    onmouseover="mouseIn ('topicals', 0)"
    onmouseout="mouseOut ('topicals', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt="| "
    name="topicals"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>Topical Index</b></font></a>&nbsp;</td>

   <td bgcolor="#553377"><a CLASS="barlink"
    href="/emc/titles/?withdrawn"
    onmouseover="mouseIn ('withdrawn', 0)"
    onmouseout="mouseOut ('withdrawn', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt="| "
    name="withdrawn"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>Withdrawn</b></font></a>&nbsp;</td>

   <td bgcolor="#333399"><a CLASS="barlink"
    href="/"
    onmouseover="mouseIn ('css', 0)"
    onmouseout="mouseOut ('css', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt="| "
    name="css"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>CSS Home</b></font></a>&nbsp;</td>

  </tr>
 </table></td>

 <td align="right"><a CLASS="barlink"
    href="/emc/titles/?search"
    onmouseover="mouseIn ('search', 0)"
    onmouseout="mouseOut ('search', 0)"><img
    width=14 height=11 border=0 src="http://www.washington.edu/classroom/emc/navarrow.gif" alt="| "
    name="search"><font face="helvetica, arial, sans-serif"
    color="#FFFFFF"><b>Search</b></font></a>&nbsp;</td>

 <td>&nbsp;</td>
</tr>
</table>
