Welcome to the WWW Edition of the Educational Media Collection--a
Non-Profit Educational Rental Collection.  We no longer publish a hard
copy edition of this Catalog.  We are not the sales source for any of
the included titles (except the <B>Tacoma Narrows Bridge Failure</B>).
However, should you be interested in purchasing any of the titles
listed, we will do our best to locate a distributor for you.  Please
contact Marisa at <a
href="mailto:risimiki@u.washington.edu">risimiki@u.washington.edu</a>.

<p>The newest films, videocassettes and laserdiscs obtained by <a
href="http://www.washington.edu/classroom/">Classroom Support
Services'</a> Educational Media Collection are indicated by having
their titles in <b>Bold</b> face.

<p>We continue to update the Collection as we replace old 16mm prints
with videocassettes, laserdiscs or DVDs on a regular basis.  As a
result, it is very important that you note the media for the titles
which interest you.

<P>Restrictions(*): Materials with an asterisk (*) behind the title
are restricted.  Specific use limitations are indicated at the
conclusion of the catalog description of that particular title.
Distributor contractual requirements do not permit exceptions to the
stated restrictions.
<br>Note: As of July 1, 2002, the University of Washington Educational
Media Collection is only renting items in its collection to
educational institutions (K-20), governmental agencies, and previous
customers.  This change is due to increased concerns about maintaining
the integrity of the collection.

<P>The classroom-use restriction placed on some video materials,
usually feature films, must be stringently observed.  Classroom use,
in this instance, is defined as direct face-to-face instruction in a
classroom environment in an educational institution.  Lack of public
performance rights prevents us from circulating classroom-use videos
to individuals and/or organizations.

<P>Videocassettes with a [Letterboxed] indication at the end of the
description are titles with the director's/producer's original
projection aspect ratio.  The titles have not been reformatted to
fit the television screen.  The black bands at the top and the bottom
of the picture are natural.

<p><B>NOTE</B>: All 3/4" U-Matic videocassettes have been withdrawn
from the Collection.  Active/historical titles have been transferred
to VHS format.  Please check the list of <a
href="titles.php?withdrawn=1">withdrawn titles</a> for titles that are
no longer in the Collection.

<p>Historical Collection: This highly selective collection within the
Collection contains materials which, though out-of-date or
out-of-print, are of historical interest.  The indication of
(Historical Collection) at the beginning of a catalog description
indicates inclusion in this very special collection.  Materials may be
missing some footage and/or opening/closing credits, however, the
content has been deemed of such importance that it must be retained.

<ul>
 <li><a href="titles.php">Alphabetic List of Titles</a>
 <li><a href="titles.php?new=1">New Titles (Added within the past year)</a>
 <li><a href="titles.php?abstracts=1&index=1">Abstracts of Titles</a>
 <ul>
  <li><a href="titles.php?search=&abstracts=1">Search the Abstracts</a>
 </ul>
 <li><a href="topics.php">Topical Index</a>
 <li><a href="titles.php?withdrawn=1">Titles Withdrawn (since 1991)</a>
</ul>

<B>COPYRIGHT WARNING:</B>

<P>All materials in the University of Washington Educational Media
Collection are protected by copyright regulations.  Persons and
organizations who violate these copyright protections are subject to
both criminal and civil action.

<P>Copyright violations include the making of unauthorized copies of
protected videotapes or films, and the broadcast of audio tapes,
videotapes or films without proper clearance.  Admissions, including
donations, may not be charged.

<P>The Educational Media Collection, Classroom Support Services and the
University of Washington request your judicious observance of
copyright regulations.

<P>It should be noted that due to Customs Regulations and Copyright, EMC
is unable to ship rental materials outside of the United States.  Should
you wish to purchase a video/film we have in our Collection, we will be
pleased to check our records and let you know where we purchased our prints.

<P>Click here for the full text of the Approved <a
href="http://www.washington.edu/classroom/emc/fairuse.html">Fair Use
Guidelines for Educational Multimedia</a>.

<P><B>A FEW REMINDERS:</b>

<P>Collection materials are intended for University-level instruction
and have been screened and evaluated by University of Washington
faculty members and acquired on their recommendation for use in campus
instruction.  University of Washington faculty interested in
evaluating new eductional media with the intent towards acquisition by
the Educational Media Collection should contact us at <a
href="mailto:risimiki@u.washington.edu">risimiki@u.washington.edu</a>.

<P>Materials considered satisfactory for university teaching may not
be suitable for other groups.  To determine suitability, borrowers are
invited to preview materials on campus upon prior arrangement.
No-charge previews at off-campus sites are not available.

<P>To obtain further information about the Educational Media
Collection, to schedule on-campus preview of our materials, or to
schedule a film, contact us at <A
HREF="mailto:risimiki@u.washington.edu">risimiki@u.washington.edu</A>.

<P>Formal Address:

<p>
Educational Media Collection<BR>
Media Scheduling  (or Catalog and Reference or Preview)<BR>
Box 353095<BR>
University of Washington<BR>
Seattle, WA   98195-3095</B>

<P>
Scheduling: <B> (206)543-9909</B><BR>
Reference:  <B> (206)543-9907</B>

<P>
FAX:        <B> (206)616-6501</B>

<p>
<B>Other University of Washington campus media sources:</b>
<UL>
  <li>The <a href="http://www.lib.washington.edu/Music/">Music Library</a> has
      an audio/video collection and is equipped with a listening center.
  <li><a href="http://www.lib.washington.edu/Media/">
      University Libraries Media Center</a>
  <li><a href="http://depts.washington.edu/reecas/outreach/material.htm">
      Russian, East European and Central Asian Studies Center</a>
</ul>

