<p>
The following is a list of the films, videocassettes, and laserdiscs obtained
by the Educational Media Collection within the past year.

<p>
Both series titles and their individual titles within the series are 
listed for easier cross-reference.

<UL type=circle>
<LI>(NOTE:  Titles with "use restrictions" are marked with an <B>*</B>.  
        These restrictions
        are the result of contractual limitations imposed by the vendor.
        They are definite and may not be ignored.)<P>

</UL>
