<p>
The following is a list of the films, videocassettes, and laserdiscs obtained
by the Educational Media Collection.

<P>
Both series titles and their individual titles within the series are 
listed for easier cross-reference.

<UL type=circle>
<LI>(NOTE:  Titles with "use restrictions" are marked with an <B>*</B>.  
        These restrictions
        are the result of contractual limitations imposed by the vendor.
        They are definite and may not be ignored.)<P>
<LI>The word (<B>Silent</B>) occurs after some titles listed below.  
These are 16mm films which must/should be projected at silent speed, 
ie. 18 frames per second.  Please check to see that you have 
the proper projection equipment.  <I>Note</I>:  These titles are being 
replaced and removed from the Collection on a gradual basis, thus eliminating
the need for special projection equipment.<P>
</UL>
